CREATE TABLE membership_type (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_membership_type PRIMARY KEY (id),
    CONSTRAINT uk_membership_type_name UNIQUE (name)
);

CREATE INDEX idx_membership_type_name ON membership_type (name);

INSERT INTO membership_type (name) VALUES
('BASIC'),
('EXTRA'),
('PREMIUM');

ALTER TABLE members
ADD COLUMN membership_type_id BIGINT NULL;

ALTER TABLE members
ADD CONSTRAINT fk_members_membership_type
    FOREIGN KEY (membership_type_id) REFERENCES membership_type (id)
    ON DELETE SET NULL;

CREATE INDEX idx_members_membership_type_id ON members (membership_type_id);
